apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01df005278c16e48f

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvclaim-mysql
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc