apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-mysql
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc